-- MySQL Script generated by MySQL Workbench
-- Tue Nov 11 06:47:41 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema timesules
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `timesules` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `timesules` ;

-- -----------------------------------------------------
-- Table `timesules`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`users` ;

CREATE TABLE IF NOT EXISTS `timesules`.`users` (
  `user_id` INT(10) NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(100) NOT NULL,
  `user_password` VARCHAR(50) NOT NULL,
  `user_first` VARCHAR(50) NOT NULL,
  `user_middle` VARCHAR(50) NOT NULL,
  `user_last` VARCHAR(50) NOT NULL,
  `user_age` DATE NOT NULL,
  `user_gender` TINYINT(1) NOT NULL,
  `user_avatar` VARCHAR(45) NOT NULL,
  `user_ip` VARCHAR(50) NOT NULL,
  `user_ban` TINYINT(1) NOT NULL DEFAULT 0,
  `user_conf` VARCHAR(50) NOT NULL,
  `user_notifications` TEXT NOT NULL,
  `user_prefs` BIT(5) NOT NULL DEFAULT b'11111',
  `hash` VARCHAR(32) NOT NULL,
  `active` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  INDEX `email` (`user_email` ASC),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesules`.`capsules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`capsules` ;

CREATE TABLE IF NOT EXISTS `timesules`.`capsules` (
  `cap_id` INT NOT NULL AUTO_INCREMENT,
  `cap_email_to` VARCHAR(100) NOT NULL,
  `cap_title` VARCHAR(200) NOT NULL,
  `cap_msg` TEXT NOT NULL,
  `cap_time` DATETIME NOT NULL,
  `cap_lock` DATE NOT NULL,
  `cap_release` DATE NOT NULL,
  `cap_hidden` TINYINT NOT NULL DEFAULT 0,
  `cap_draft` TINYINT NOT NULL DEFAULT 0,
  `cap_vis` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`cap_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesules`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`groups` ;

CREATE TABLE IF NOT EXISTS `timesules`.`groups` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  `group_avatar` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesules`.`user_owns_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`user_owns_groups` ;

CREATE TABLE IF NOT EXISTS `timesules`.`user_owns_groups` (
  `group_id` INT NOT NULL,
  `user_id` INT(10) NOT NULL,
  `user_role` VARCHAR(150) NOT NULL DEFAULT 'member',
  PRIMARY KEY (`group_id`, `user_id`),
  INDEX `fk_user_owns_group_user1_idx` (`user_id` ASC),
  INDEX `fk_user_owns_group_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_user_owns_group_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `timesules`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_owns_group_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `timesules`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesules`.`user_has_contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`user_has_contacts` ;

CREATE TABLE IF NOT EXISTS `timesules`.`user_has_contacts` (
  `user_id` INT(10) NOT NULL,
  `contact_id` INT(10) NOT NULL,
  PRIMARY KEY (`user_id`, `contact_id`),
  INDEX `fk_user_has_user_user2_idx` (`contact_id` ASC),
  INDEX `fk_user_has_user_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_contacts_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `timesules`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_contacts_contact`
    FOREIGN KEY (`contact_id`)
    REFERENCES `timesules`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesules`.`user_has_capsules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`user_has_capsules` ;

CREATE TABLE IF NOT EXISTS `timesules`.`user_has_capsules` (
  `cap_id` INT NOT NULL,
  `user_id` INT(10) NOT NULL,
  PRIMARY KEY (`cap_id`, `user_id`),
  INDEX `fk_user_has_capsules_users1_idx` (`user_id` ASC),
  INDEX `fk_user_has_capsules_capsules1_idx` (`cap_id` ASC),
  CONSTRAINT `fk_user_has_capsules_cap`
    FOREIGN KEY (`cap_id`)
    REFERENCES `timesules`.`capsules` (`cap_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_capsules_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `timesules`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesules`.`group_has_capsules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`group_has_capsules` ;

CREATE TABLE IF NOT EXISTS `timesules`.`group_has_capsules` (
  `cap_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`cap_id`, `group_id`),
  INDEX `fk_group_has_capsules_groups1_idx` (`group_id` ASC),
  INDEX `fk_group_has_capsules_capsules1_idx` (`cap_id` ASC),
  CONSTRAINT `fk_group_has_capsules_cap`
    FOREIGN KEY (`cap_id`)
    REFERENCES `timesules`.`capsules` (`cap_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_capsules_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `timesules`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesules`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`notifications` ;

CREATE TABLE IF NOT EXISTS `timesules`.`notifications` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`notification_id`, `user_id`),
  INDEX `fk_notifications_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_notifications_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `timesules`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesules`.`user_has_notifcations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`user_has_notifcations` ;

CREATE TABLE IF NOT EXISTS `timesules`.`user_has_notifcations` (
  `user_id` INT(10) NOT NULL,
  `notification_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `notification_id`),
  INDEX `fk_notifications_has_users_users1_idx` (`user_id` ASC),
  INDEX `fk_notifications_has_users_notifications1_idx` (`notification_id` ASC),
  CONSTRAINT `fk_user_has_notifcations_notification`
    FOREIGN KEY (`notification_id`)
    REFERENCES `timesules`.`notifications` (`notification_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_notifcations_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `timesules`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesules`.`attachments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesules`.`attachments` ;

CREATE TABLE IF NOT EXISTS `timesules`.`attachments` (
  `attachment_id` INT NOT NULL AUTO_INCREMENT,
  `attachment_image_link` VARCHAR(100) NOT NULL,
  `attachment_media_link` VARCHAR(100) NOT NULL,
  `attachment_text` TEXT NOT NULL,
  `cap_id` INT NOT NULL,
  PRIMARY KEY (`attachment_id`, `cap_id`),
  INDEX `fk_attachments_capsules1_idx` (`cap_id` ASC),
  CONSTRAINT `fk_attachments_capsules1`
    FOREIGN KEY (`cap_id`)
    REFERENCES `timesules`.`capsules` (`cap_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tables from old schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Bug Reports
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bugs`;
CREATE TABLE IF NOT EXISTS `bugs` (
  `bug_id` int(10) NOT NULL AUTO_INCREMENT,
  `bug_page` varchar(50) NOT NULL,
  `bug_msg` text NOT NULL,
  `bug_user` int(10) NOT NULL,
  `bug_date` int(10) NOT NULL,
  PRIMARY KEY (`bug_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
-- -----------------------------------------------------
-- User comments
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comments`;
CREATE TABLE IF NOT EXISTS `comments` (
  `com_id` int(10) NOT NULL AUTO_INCREMENT,
  `com_type` int(1) NOT NULL,
  `com_user` int(10) NOT NULL,
  `com_post` int(10) NOT NULL,
  `com_date` int(10) NOT NULL,
  `com_comment` varchar(500) NOT NULL,
  PRIMARY KEY (`com_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
-- -----------------------------------------------------
-- Bug Tracker
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debug_tracker`;
CREATE TABLE IF NOT EXISTS `debug_tracker` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `user` int(10) NOT NULL,
  `page` varchar(50) NOT NULL,
  `get_data` text NOT NULL,
  `post_data` text NOT NULL,
  `queries` text NOT NULL,
  `user_data` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
-- -----------------------------------------------------
-- Bug Tickets
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tickets`;
CREATE TABLE IF NOT EXISTS `tickets` (
  `ticket_id` int(10) NOT NULL AUTO_INCREMENT,
  `ticket_name` varchar(200) NOT NULL,
  `ticket_email` varchar(200) NOT NULL,
  `ticket_area` varchar(50) NOT NULL,
  `ticket_msg` text NOT NULL,
  `ticket_user` int(10) NOT NULL,
  `ticket_date` int(10) NOT NULL,
  PRIMARY KEY (`ticket_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
-- -----------------------------------------------------
-- Front Page Capsule
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sendacapsule`;
CREATE TABLE IF NOT EXISTS `sendacapsule` (
  `cap_id` int(10) NOT NULL AUTO_INCREMENT,
  `cap_email` varchar(100) NOT NULL,
  `cap_subj` varchar(100) NOT NULL,
  `cap_msg` varchar(500) NOT NULL,
  `cap_time` int(10) NOT NULL,
  PRIMARY KEY (`cap_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
